name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build
        
    - name: Build JAR
      run: |
        ./gradlew jar
          - name: Download Launch4j
      run: |
        wget -O launch4j.zip "https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-linux-x64.zip/download"
        unzip launch4j.zip
        chmod +x launch4j/launch4j
        
    - name: Create Launch4j config
      run: |
        cat > launch4j-config.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <launch4jConfig>
          <dontWrapJar>false</dontWrapJar>
          <headerType>gui</headerType>
          <jar>build/libs/File-encryption-anaylsis.jar</jar>
          <outfile>build/exe/File-encryption-anaylsis.exe</outfile>
          <errTitle>File Encryption Analysis</errTitle>
          <chdir>.</chdir>
          <priority>normal</priority>
          <downloadUrl>https://adoptopenjdk.net/</downloadUrl>
          <supportUrl></supportUrl>
          <stayAlive>false</stayAlive>
          <restartOnCrash>false</restartOnCrash>
          <manifest></manifest>
          <icon>src/main/resources/File Encryption Analysis.ico</icon>
          <jre>
            <path></path>
            <bundledJre64Bit>false</bundledJre64Bit>
            <minVersion>11</minVersion>
            <maxVersion></maxVersion>
            <jdkPreference>preferJre</jdkPreference>
            <runtimeBits>64/32</runtimeBits>
          </jre>
        </launch4jConfig>
        EOF
        - name: Create EXE with Launch4j
      run: |
        mkdir -p build/exe
        ./launch4j/launch4j launch4j-config.xml

    - name: Create Output Directory
      run: mkdir -p release

    - name: Copy Build Artifacts
      run: |
        cp build/libs/File-encryption-anaylsis.jar release/
        cp build/exe/File-encryption-anaylsis.exe release/
        - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: file-encryption-analysis-builds
        path: |
          release/File-encryption-anaylsis.jar
          release/File-encryption-anaylsis.exe
